### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by sonnius** [mgee/slimfish#3]
Doing a fresh install fails:

rob@Robs-MBP ~> fisher add mgee/slimfish
fetching https://codeload.github.com/mgee/slimfish/tar.gz/master
linking ~/.config/fish/functions/fish_prompt.fish
linking ~/.config/fish/functions/fish_prompt_async.fish
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/rob/.config/fish/functions/gitline.py': [Errno 2] No such file or directory
linking ~/.config/fish/functions/fish_right_prompt.fish
fetching https://codeload.github.com/fisherman/humanize_duration/tar.gz/master
fetching https://codeload.github.com/mgee/gitline/tar.gz/master
fisher: cannot add github.com/fisherman/humanize_duration -- is this a valid package?
added 2 packages in 2.73s
~ ∙ /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/rob/.config/fish/functions/gitline.py': [Errno 2] No such file or directory

**Comment by mengelbrecht** [comment]
Thanks for reporting this. I fixed the issue in the master branch. 
Please remove the slimfish package and reinstall it to fix it.

**Comment by sonnius** [comment]
Works as expected, thx!
